[[phps]]
  path = "backend"
  build = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "composer install --no-dev --optimize-autoloader"
  ]
  start = "php -S 0.0.0.0:$PORT -t public"
