nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://www.helpex.com:22193']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        max_age: 3600
        allow_credentials: true
        hosts: ['^www\.helpex\.com:22193$']
    paths:
        '^/api/':
            origin_regex: false
            allow_origin: ['http://www.helpex.com:22193']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
            hosts: ['^www\.helpex\.com:22193$']
