nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https?://(localhost|www\.helpex\.com|api\.helpex\.com)(:[0-9]+)?$']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        max_age: 3600
        allow_credentials: true
        hosts: ['^https?://(localhost|www\.helpex\.com|api\.helpex\.com)(:[0-9]+)?$']
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['^https?://(localhost|www\.helpex\.com|api\.helpex\.com)(:[0-9]+)?$']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
            hosts: ['^https?://(localhost|www\.helpex\.com|api\.helpex\.com)(:[0-9]+)?$'] 