security:
    # ... otras configuraciones
    
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: correo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Configuración para las solicitudes preflight OPTIONS
        cors_preflight:
            pattern: ^/api/
            methods: [OPTIONS]
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            custom_authenticator: App\Security\TokenAuthenticator
            
            # Deshabilitamos json_login ya que manejamos el login en el controlador
            logout:
                path: /api/logout
            
            # Punto de entrada para autenticación fallida
            entry_point: App\Security\TokenAuthenticator

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: PUBLIC_ACCESS }
        - { path: ^/api/products/search, roles: PUBLIC_ACCESS }
        - { path: ^/api/professionals/search, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER } 